spring:
  datasource:
    url: jdbc:h2:mem:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari.jdbc-url: jdbc:h2:mem:~/test;MODE=MYSQL

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

management:
  server:
    port: 8081
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true

tabling:
  security-credentials:
    login-path: "/login"
    login-method: "POST"
    member-add-path: "/members"
    member-add-method: "POST"
    bytes-encryptor-password: "This is a password!"
    bytes-encryptor-salt: "0123456f"
