spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tabling?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: developer
    password: 1111
    hikari:
      maximum-pool-size: 200

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql

management:
  server:
    port: 8081
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true

tabling:
  security-credentials:
    login-path: "/login"
    login-method: "POST"
    member-add-path: "/members"
    member-add-method: "POST"
    bytes-encryptor-password: "This is a password!"
    bytes-encryptor-salt: "0123456f"
