tabling API 명세서입니다.

== 로그인 성공

operation::auth-controller-rest-docs-test/login-success[snippets="http-request,http-response"]

== 로그아웃 성공

operation::auth-controller-rest-docs-test/logout-success[snippets="http-request,http-response"]

== 회원가입 성공

operation::member-controller-rest-docs-test/add-user[snippets="http-request,http-response"]

== 가게 등록 성공

operation::store-controller-rest-docs-test/add-store-success[snippets="http-request,http-response"]

== 가게 수정 성공

operation::store-controller-rest-docs-test/update-store-success[snippets="http-request,http-response"]

== 가게 삭제 성공

operation::store-controller-rest-docs-test/delete-store-success[snippets="http-request,http-response"]

== 가게 단건 조회 성공

operation::store-controller-rest-docs-test/find-store-success[snippets="http-request,http-response"]

== 가게 페이지 조회 성공

operation::store-controller-rest-docs-test/find-store-page-success[snippets="http-request,http-response"]

== 운영 시간 등록 성공

operation::business-hour-controller-rest-docs-test/success-add[snippets="http-request,http-response"]

== 운영 시간 수정 성공

operation::business-hour-controller-rest-docs-test/success-update[snippets="http-request,http-response"]

== 운영 시간 삭제 성공

operation::business-hour-controller-rest-docs-test/success-delete[snippets="http-request,http-response"]

== 운영 시간 단건 조회 성공

operation::business-hour-controller-rest-docs-test/success-find[snippets="http-request,http-response"]

== 운영 시간 페이지 조회 성공

operation::business-hour-controller-rest-docs-test/success-find-page[snippets="http-request,http-response"]