name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3306
          container port: 3306
          mysql database: 'tabling'
          mysql user: 'developer'
          mysql password: '1111'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - run: ./gradlew build
