name: Create Jira issue
on:
  issues: 
    types: [opened]
    
jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env: 
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    
    - name: Create Issue 
      uses: atlassian/gajira-create@v3
      with:
        project: tabling
        issuetype: Task
        summary: '${{ github.event.issue.title }}'
        description: '${{ github.event.issue.html_url }}'
